version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: netflix-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: netflix-rabbitmq
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  minio:
    image: quay.io/minio/minio
    container_name: netflix-minio
    ports:
      - "9000:9000" # API access
      - "9001:9001" # Web UI
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

volumes:
  minio_data:
